sonar.projectKey=Zellione_comfyui-tiny-model-manager
sonar.organization=zellione

sonar.sources=py,frontend/src,js
sonar.tests=tests,frontend/src
sonar.test.inclusions=tests/**,frontend/src/**/*.spec.ts
sonar.exclusions=frontend/node_modules/**,web/**

sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
